- name: variables
  hosts: localhost
  tasks:
    - name: print information
      ansible.builtin.debug:
          msg: "Hi, Iam Hemanth Kumar doing  devops course Near trainer shivakumar and course duration is 160Hrs"




