- name: variables
  hosts: localhost
  vars: #variable declaration or defintion  
    Course: Devops
    Trainer: Shiva 
    Duration: 100Hrs
  tasks:
    - name: print over ride information
      vars:
        Course: Ansible
        Trainer: jhone
        Duration: 50Hrs
      ansible.builtin.debug:
          msg: "Hi, Iam Hemanth Kumar doing {{Course}} course Near trainer {{Trainer}} and course duration is {{Duration}}"

    - name: print over ride information
      ansible.builtin.debug:
          msg: "Hi, Iam Hemanth Kumar doing {{Course}} course Near trainer {{Trainer}} and course duration is {{Duration}}"



